apiVersion: v1
kind: Service
metadata:
  name: {{ include "clahan.fullname" . }}-exam
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: exam
spec:
  type: {{ if eq "exam" "frontend" }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 4004
      targetPort: 4004
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "clahan.name" . }}-exam
    app.kubernetes.io/instance: {{ .Release.Name }}
