apiVersion: v1
kind: Service
metadata:
  name: {{ include "clahan.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ if eq "frontend" "frontend" }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 5173
      targetPort: 5173
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "clahan.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
