apiVersion: v1
kind: Service
metadata:
  name: {{ include "clahan.fullname" . }}-notification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
spec:
  type: {{ if eq "notification" "frontend" }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 4006
      targetPort: 4006
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "clahan.name" . }}-notification
    app.kubernetes.io/instance: {{ .Release.Name }}
