apiVersion: v1
kind: Service
metadata:
  name: {{ include "clahan.fullname" . }}-proctoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: proctoring
spec:
  type: {{ if eq "proctoring" "frontend" }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - name: http
      port: 4005
      targetPort: 4005
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "clahan.name" . }}-proctoring
    app.kubernetes.io/instance: {{ .Release.Name }}
