apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clahan.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.admin.clientId | quote }}
automountServiceAccountToken: true
