apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clahan.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: {{ .Values.azure.workloadIdentity.auth.clientId | quote }}
automountServiceAccountToken: true
