apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clahan.fullname" . }}-judge0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: judge0
  annotations:
    azure.workload.identity/use: "true"
automountServiceAccountToken: false
