apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "clahan.fullname" . }}-ai-models
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.ai.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.storage.ai.size | quote }}
  storageClassName: {{ .Values.storage.storageClassName | default "azureblob-nfs-premium" | quote }}
