apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "clahan.fullname" . }}-auth-spc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useClientID: "true"
    clientID: {{ .Values.azure.workloadIdentity.auth.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: jwt-access-secret
          objectType: secret
        - |
          objectName: jwt-refresh-secret
          objectType: secret
        - |
          objectName: redis-connection-string
          objectType: secret
  secretObjects:
    - secretName: {{ include "clahan.fullname" . }}-auth-secret
      type: Opaque
      data:
        - objectName: db-connection-string
          key: DATABASE_URL
        - objectName: jwt-access-secret
          key: JWT_ACCESS_SECRET
        - objectName: jwt-refresh-secret
          key: JWT_REFRESH_SECRET
        - objectName: redis-connection-string
          key: REDIS_URL
