apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "clahan.fullname" . }}-notification-spc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useClientID: "true"
    clientID: {{ .Values.azure.workloadIdentity.notification.clientId | quote }}
    keyvaultName: {{ .Values.azure.keyVaultName | quote }}
    tenantId: {{ .Values.azure.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: smtp-user
          objectType: secret
        - |
          objectName: smtp-pass
          objectType: secret
  secretObjects:
    - secretName: {{ include "clahan.fullname" . }}-notification-secret
      type: Opaque
      data:
        - objectName: redis-connection-string
          key: REDIS_URL
        - objectName: smtp-user
          key: SMTP_USER
        - objectName: smtp-pass
          key: SMTP_PASS
