{{- if .Values.proctoring.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "clahan.fullname" . }}-proctoring
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: proctoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "clahan.fullname" . }}-proctoring
  minReplicas: {{ .Values.proctoring.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.proctoring.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.proctoring.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
