{{- if .Values.auth.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "clahan.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  minAvailable: {{ .Values.auth.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "clahan.name" . }}-auth
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
