# kubernetes/secrets.yaml

apiVersion: v1
kind: Secret
metadata:
  name: clahan-secrets
  namespace: production
type: Opaque
data:
  DATABASE_URL: UkVQTEFDRV9XSVRIX1JFQUxfREJfVVJM
  REDIS_URL: UkVQTEFDRV9XSVRIX1JFQUxfUkVESVNfVVJM
  JWT_ACCESS_SECRET: UkVQTEFDRV9XSVRIX0pXVF9BQ0NFU1NfU0VDUkVU
  JWT_REFRESH_SECRET: UkVQTEFDRV9XSVRIX0pXVF9SRUZSRVNIX1NFQ1JFVA==
  SMTP_HOST: c210cC5nbWFpbC5jb20=
  SMTP_PORT: NTg3
  SMTP_USER: UkVQTEFDRV9XSVRIX1NNVFBfVVNFUg==
  SMTP_PASS: UkVQTEFDRV9XSVRIX1NNVFBfUEFTUw==
  SMTP_FROM: UkVQTEFDRV9XSVRIX1NNVFBfRlJPTQ==
  SENDGRID_API_KEY: UkVQTEFDRV9XSVRIX1NFTkRHUklEX0tFWQ==
  SENDGRID_FROM: UkVQTEFDRV9XSVRIX1NFTkRHUklEX0ZST00=
