apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clahan.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
data:
  PORT: "4001"
  NODE_ENV: {{ .Values.global.environment | quote }}
