apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clahan.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  PORT: "5173"
