apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clahan.fullname" . }}-ollama
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
    app.kubernetes.io/component: ollama
data:
  PORT: "11434"
