apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "clahan.fullname" . }}-deny-all-default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clahan.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
